name: Build and Deploy to App Engine
run-name: Deploy to App Engine by @${{ github.actor }}
on:
  workflow_dispatch: 
  # push:
  #   branches: [ "gcp-deploy" ]

jobs:
  build-image-and-deploy:
    runs-on: ubuntu-latest
    environment: staging

    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Google auth'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}'
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}'

      - name: 'Deploy to App Engine'
        id: 'deploy'
        uses: 'google-github-actions/deploy-appengine@v1'
        with: 
          project_id: '${{ secrets.GCLOUD_PROJECT_ID }}'
          deliverables: app.yaml
          


